config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets
  # get '/users/sign_out' => 'devise/sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
  end

  def create
    tweet = Tweet.create(text: tweet_params[:text], user_id:current_user.id)
    redirect_to action: 'index'
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
    redirect_to action: 'index'
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  private
  def tweet_params
    params.permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @tweets = current_user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>MiniApp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tag %>
    <!-- Compiled and minified CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

   <!-- Compiled and minified JavaScript -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

   <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script> 
  
  </head>

  <body>
  <nav class="p#ee6e73">
    <div class="nav-wrapper">
      <%=link_to "Blog", root_path, class: 'get', class: "brand-logo center" %>
      <% if user_signed_in? %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%=link_to "SignOut", destroy_user_session_path, method: :delete %></li>
          <li><%=link_to "New", new_tweet_path, class: 'post' %></li>
        <% else %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%=link_to "SignIn", new_user_session_path, class: 'get' %></li>
          <li><%=link_to "SignUp", new_user_registration_path, class: 'post' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
    <%= yield %>
  <script type="text/javascript" src="./app.js"></script>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="contents row">
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <div class="card white">
        <div class="card-content grey-text">
          <span class="card-text"></span>
          <%= simple_format(tweet.text) %>
        </div>
        <div class="card-action">
          <%= link_to 'SHOW', tweet_path(tweet.id), method: :get, class: "waves-effect waves-light btn" %>
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%= link_to 'EDIT', edit_tweet_path(tweet[:id]), method: :get, class: "waves-effect waves-light btn" %>
          <%= link_to 'DELETE', tweet_path(tweet.id), method: :delete, class: "waves-effect waves-light btn" %>
        <% end %>
        </div>
      </div>
    </div>
    </div>
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h6>
      投稿が完了しました
    </h6>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h6>
      削除が完了しました。
    </h6>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <%= form_with model: @tweet do |form| %>
    <h6>
      編集
    </h6>
    <textarea cols="30" name="text" placeholder="text" rows="10"><%= @tweet.text %></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
  
</div>

<%= paginate(@tweets) %>

app/views/tweets/new.html.erb
<div class="contents row">
  <%= form_with url: tweets_path, class: :search_form do |form| %>
  <h6>
    本文
  </h6>
    <textarea placeholder="text" name="text" cols="30" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="row">
    <div class="col s12 m12">
      <div class="card white">
        <div class="card-content grey-text">
          <span class="card-text"></span>
            <%= simple_format(@tweet.text) %>
            <span class="name">
              <a href="/users/<%= @tweet.user.id %>">
                <span>投稿者</span><%= @tweet.user.nickname %>
              </a>
            </span>
        </div>
        <div class="card-action">
      <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <%= link_to 'EDIT', "/tweets/#{@tweet.id}/edit", method: :get, class: "waves-effect waves-light btn" %>
        <%= link_to 'DELETE', "/tweets/#{@tweet.id}", method: :delete, class: "waves-effect waves-light btn" %>
        </div>
      </div>
    </div>
  </div>
      <% end %>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h6>
      更新が完了しました。
    </h6>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row" >
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>